Repository checkout/checkout-api-reference, pull requests merged in 2022-05, with the labels that each got.

#516 add new 3DS third party field for Cartes Bancaires
  nas_spec/components/schemas/Payments/3dsRequest.yaml
Labels: [DONOTMERGE]

#569 Adds `3ds.challenge_indicator` to PL and HPP
  abc_spec/changelog.md
  abc_spec/components/schemas/HostedPayments/HostedPaymentsRequest.yaml
  abc_spec/components/schemas/PaymentLinks/PaymentLinksRequest.yaml
  nas_spec/changelog.md
  nas_spec/components/schemas/HostedPayments/HostedPaymentsRequest.yaml
  nas_spec/components/schemas/PaymentLinks/PaymentLinksRequest.yaml
Labels: Both

#566 [To merge on 11 May] Adds Arabic locale to PL and HPP
  abc_spec/changelog.md
  abc_spec/components/schemas/HostedPayments/HostedPaymentsRequest.yaml
  abc_spec/components/schemas/PaymentLinks/PaymentLinksRequest.yaml
  nas_spec/changelog.md
  nas_spec/components/schemas/HostedPayments/HostedPaymentsRequest.yaml
  nas_spec/components/schemas/PaymentLinks/PaymentLinksRequest.yaml
Labels: Both

#576 Removes first_name and country fields from PaymentRecipient schema
  abc_spec/components/schemas/Payments/PaymentRecipient.yaml
  nas_spec/components/schemas/Payments/PaymentRecipient.yaml
Labels: Both

#574 [To merge on 18 May] Adds Get transfer details
  nas_spec/changelog.md
  nas_spec/components/schemas/Transfers/Transfer.yaml
  nas_spec/components/schemas/Transfers/TransferStatus.yaml
  nas_spec/components/schemas/Transfers/TransferType.yaml
  nas_spec/paths/transfers@{id}.yaml
Labels: NAS

#579 Deletes ListTransfersResponse.yaml
  nas_spec/components/schemas/Transfers/ListTransfersResponse.yaml
Labels: NAS

#578 Wechat API reference private beta
  nas_spec/changelog.md
  nas_spec/components/schemas/Payments/Items.yaml
  nas_spec/components/schemas/Payments/PaymentAcceptedResponse.yaml
  nas_spec/components/schemas/Payments/PaymentRequestSource.yaml
  nas_spec/components/schemas/Payments/PaymentResponseSource.yaml
  nas_spec/components/schemas/Payments/ProcessingSettings.yaml
  nas_spec/components/schemas/Payments/RequestSources/08_PaymentRequestWeChatPaySource.yaml
  nas_spec/components/schemas/Payments/ResponseSources/03_PaymentResponseWeChatPaySource.yaml
Labels: [DONOTMERGE], BETA
